config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  resources :topics do
    resources :bookmarks
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, :only => [:show]

  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

  post :incoming, to: 'incoming#create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  has_many :likes, dependent: :destroy
  delegate :user, to: :topic
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :set_topic
  # GET /bookmarks
  # GET /bookmarks.json

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit

  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = @topic.bookmarks.new(bookmark_params)
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @topic, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    authorize(@bookmark)
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    authorize (@bookmark)
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to @topic, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:url)
    end

    def set_topic
      @topic = Topic.find(params[:topic_id])
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr>
  <td><%= bookmark.url %></td>
  <td><%= render partial: 'likes/like', locals: { bookmark: bookmark } %></td>
  </td>
  <td><%= link_to 'Edit', edit_topic_bookmark_path(bookmark.topic, bookmark) %>
  </td>
  <td><%= link_to 'Destroy', [bookmark.topic, bookmark], method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_for [@topic, @bookmark] do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', topic_bookmark_path %> |
<%= link_to 'Back', @topic %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @bookmarks %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', @topic %>

app/views/bookmarks/show.html.erb
<h3><%= @bookmark.url %></h3>



<%= link_to 'Edit', edit_topic_bookmark_path(@topic,@bookmark) %> |
<%= link_to 'Delete', [@topic, @bookmark], method: :delete %> |
<%= link_to 'Back', @topic %>