config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  resources :topics do
    resources :bookmarks
  end

  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end

  devise_for :users
  resources :users, :only => [:show]

  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

  post :incoming, to: 'incoming#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharemarks</title>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <% if user_signed_in? %>
      <div class='pull-right control-group'>Signed in as: <strong><%= current_user.username %></strong>
      </div>
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "My Profile", users_show_path %></li>
        <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
    </ul>
      <% end %>

<%= yield %>
  </div>

</body>
</html>